codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree
coverage:
  precision: 2
  range: "90..100"
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project:
      default:
        target: 90%
        threshold: 10%
github_checks:
  annotations: true
