name: Build and test the project

on: [push]

env:
  MIX_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24
        elixir-version: 1.13

    - name: Build project
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile
        mix dialyzer.build
        mix compile --warnings-as-errors

    - name: Elixir Static analysis
      run: mix dialyzer

    - name: Elixir check formatting
      run: mix format --check-formatted

    - name: Elixir Linter
      run: mix credo list --strict
